<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_ae_e4HQQEe2zsYbGoXS0Sg" name="ElaborationPLMDiagram" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_ae_e4XQQEe2zsYbGoXS0Sg" name="ElaborationPLM">
      <elements xmi:type="process:Lane" xmi:id="_ae_e4nQQEe2zsYbGoXS0Sg" name="Ordonnateurs" actor="_o4gu4HQgEe2zsYbGoXS0Sg">
        <elements xmi:type="process:StartEvent" xmi:id="_ae_e43QQEe2zsYbGoXS0Sg" name="Start1" outgoing="_ae_e-HQQEe2zsYbGoXS0Sg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ae_e5HQQEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ae_e5XQQEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ae_e5nQQEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="__8CIIHQQEe2zsYbGoXS0Sg" name="établissement ​​​des propositions de programmations budgétaires" outgoing="_66YhQHQSEe2zsYbGoXS0Sg" incoming="_ae_e-HQQEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ae_e6HQQEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ae_e6XQQEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ae_e6nQQEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ae_e63QQEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ae_e7HQQEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ae_e7XQQEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ae_e7nQQEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ae_e73QQEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="__8DWSHQQEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="__8DWSXQQEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__8DWR3QQEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__8D9UHQQEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_7-wIUHQSEe2zsYbGoXS0Sg" name="partage des propositions de programmations budgétaires" outgoing="_PEHPoHQTEe2zsYbGoXS0Sg" incoming="_66YhQHQSEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6571UXQSEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6571UHQSEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6571UnQSEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6571U3QSEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6571VHQSEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6571VXQSEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6571V3QSEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6571VnQSEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_7-xWcnQSEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_7-xWc3QSEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_7-xWcXQSEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_7-xWdHQSEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_9yoVMHQcEe2zsYbGoXS0Sg" name="réception des invitations à établir les propositions de recettes et de dépenses pour l'année budgétaire suivante" incoming="_88LOUHQcEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_87_BEXQcEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_87_BEHQcEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_87_BEnQcEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_87_BE3QcEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_87_BFHQcEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_87_BFXQcEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_87_BF3QcEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_87_BFnQcEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_9ypjVnQcEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_9ypjV3QcEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_9ypjVXQcEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_9ypjWHQcEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_I26GgHQTEe2zsYbGoXS0Sg" name="Chef du Gouvernement" actor="_3ZkkkHQgEe2zsYbGoXS0Sg">
        <elements xmi:type="process:Task" xmi:id="_Q4QGwHQTEe2zsYbGoXS0Sg" name="réception des propositions des ordonnateurs" outgoing="_MsQK8HQUEe2zsYbGoXS0Sg" incoming="_PEHPoHQTEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PD3YAXQTEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PD3YAHQTEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PD3YAnQTEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PD3YA3QTEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PD3YBHQTEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PD3YBXQTEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PD3YB3QTEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PD3YBnQTEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Q4Qt1HQTEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_Q4Qt1XQTEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Q4Qt03QTEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Q4Qt1nQTEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_tYlPgHQaEe2zsYbGoXS0Sg" name="invitation des ordonnateurs à établir leurs propositions de recettes et de dépenses pour l'année budgétaire suivante" outgoing="_88LOUHQcEe2zsYbGoXS0Sg _KFcKoHQdEe2zsYbGoXS0Sg" incoming="_quKQoHQaEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qt9cUXQaEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qt9cUHQaEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qt9cUnQaEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qt9cU3QaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qt9cVHQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qt9cVXQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qt9cV3QaEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qt9cVnQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_tYl2mXQaEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_tYl2mnQaEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_tYl2mHQaEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_tYl2m3QaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_siqYUHQTEe2zsYbGoXS0Sg" name="départements ministériels et institution" actor="_8N4oIHQgEe2zsYbGoXS0Sg">
        <elements xmi:type="process:Task" xmi:id="_NoqI0HQUEe2zsYbGoXS0Sg" name="transfert les propositions des ordonnateurs au ministère chargé des finances" outgoing="_mdfe8HQVEe2zsYbGoXS0Sg" incoming="_MsQK8HQUEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Mr_FMXQUEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Mr_FMHQUEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Mr_FMnQUEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Mr_FM3QUEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Mr_FNHQUEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Mr_FNXQUEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Mr_FN3QUEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Mr_FNnQUEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Noqv6XQUEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_Noqv6nQUEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Noqv6HQUEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Noqv63QUEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_L2R2IHQdEe2zsYbGoXS0Sg" name="préparation d'une proposition de la Phase d’élaboration et d’arbitrage" outgoing="_kIHCUHQdEe2zsYbGoXS0Sg" incoming="_KFcKoHQdEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KFRLgXQdEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KFRLgHQdEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KFRLgnQdEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KFRLg3QdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KFRLhHQdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KFRLhXQdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KFRLh3QdEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KFRLhnQdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_L2SdOXQdEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_L2SdOnQdEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_L2SdOHQdEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_L2SdO3QdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_egAgcHQUEe2zsYbGoXS0Sg" name="Commissions de programmation et de performance" actor="_yY0ngHQgEe2zsYbGoXS0Sg">
        <elements xmi:type="process:Task" xmi:id="_6viJ4HQXEe2zsYbGoXS0Sg" name="examen des propositions" outgoing="_t2qaAHQXEe2zsYbGoXS0Sg" incoming="_mdfe8HQVEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mdUf0XQVEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mdUf0HQVEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mdUf0nQVEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_mdUf03QVEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_mdUf1HQVEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_mdUf1XQVEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_mdUf13QVEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_mdUf1nQVEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_6viw-XQXEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_6viw-nQXEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_6viw-HQXEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_6viw-3QXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_HsgokHQWEe2zsYbGoXS0Sg" name="ministre chargé des finances" actor="_K5A_0HQhEe2zsYbGoXS0Sg">
        <elements xmi:type="process:Task" xmi:id="_5IO04HQXEe2zsYbGoXS0Sg" name="exposition en Conseil du gouvernement, la programmation triennale des ressources et des charges de l'Etat" outgoing="_-sg80HQXEe2zsYbGoXS0Sg" incoming="_3NPu4HQXEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3NEvwXQXEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3NEvwHQXEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3NEvwnQXEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3NEvw3QXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3NEvxHQXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_3NEvxXQXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_3NEvx3QXEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_3NEvxnQXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_5IPb-XQXEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_5IPb-nQXEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_5IPb-HQXEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_5IPb-3QXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_5zeKQHQXEe2zsYbGoXS0Sg" name="exposition en Conseil du gouvernement, l'état d'avancement de l'exécution de la loi de finances en cours à la date du 30 juin" outgoing="_3NPu4HQXEe2zsYbGoXS0Sg" incoming="_t2qaAHQXEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_t2eMwXQXEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_t2eMwHQXEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_t2ez0HQXEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_t2ez0XQXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_t2ez0nQXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_t2ez03QXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_t2ez1XQXEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_t2ez1HQXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_5zfYYHQXEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_5zfYYXQXEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_5zexWHQXEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_5zfYYnQXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AQQAcHQYEe2zsYbGoXS0Sg" name="exposition en Conseil du gouvernement, les grandes lignes du projet de loi de finances de l'année suivante" outgoing="_HVO0MHQaEe2zsYbGoXS0Sg" incoming="_-sg80HQXEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-sSTUXQXEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-sSTUHQXEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-sSTUnQXEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-sSTU3QXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-sSTVHQXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-sSTVXQXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-sSTV3QXEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-sSTVnQXEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_AQROlnQYEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_AQROl3QYEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_AQROlXQYEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_AQROmHQYEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_dV0WgHQaEe2zsYbGoXS0Sg" name="exposition devant les commissions des finances du Parlement, le cadre général de préparation du projet de loi de finances de l'année suivante" outgoing="_quKQoHQaEe2zsYbGoXS0Sg" incoming="_WUawUHQaEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WUQ_UXQaEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WUQ_UHQaEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WUQ_UnQaEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_WUQ_U3QaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_WUQ_VHQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_WUQ_VXQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_WUQ_V3QaEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_WUQ_VnQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_dV1ko3QaEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_dV1kpHQaEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_dV1konQaEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_dV1kpXQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_8fziwHQZEe2zsYbGoXS0Sg" name="commissions des finances du Parlement" actor="_Po4BMHQhEe2zsYbGoXS0Sg">
        <elements xmi:type="process:Task" xmi:id="_IkVEkHQaEe2zsYbGoXS0Sg" name="exposition de l'évolution de l'économie nationale" outgoing="_J_FLUHQaEe2zsYbGoXS0Sg" incoming="_HVO0MHQaEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HVCm8HQaEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HVB_4HQaEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HVCm8XQaEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HVCm8nQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HVCm83QaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HVCm9HQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HVCm9nQaEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HVCm9XQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_IkVrqXQaEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_IkVrqnQaEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_IkVrqHQaEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_IkVrq3QaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_KnP-kHQaEe2zsYbGoXS0Sg" name="exposition des données relatives à la politique économique et financière et la programmation budgétaire triennale globale." outgoing="_WUawUHQaEe2zsYbGoXS0Sg" incoming="_J_FLUHQaEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_J-3v8XQaEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_J-3v8HQaEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_J-3v8nQaEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_J-4XAHQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_J-4XAXQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_J-4XAnQaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_J-4XBHQaEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_J-4XA3QaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_KnQlqXQaEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_KnQlqnQaEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_KnQlqHQaEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_KnQlq3QaEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_b5_xYHQdEe2zsYbGoXS0Sg" name="Ministère de l’EcoFinances et autres Ministères" actor="_Uw2AkHQhEe2zsYbGoXS0Sg">
        <elements xmi:type="process:Task" xmi:id="_mD-SEHQdEe2zsYbGoXS0Sg" name="préparation d'une commissions budgétaires et arbitrage de la Phase d’élaboration et d’arbitrage" outgoing="_162rMHQdEe2zsYbGoXS0Sg" incoming="_kIHCUHQdEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kH61EXQdEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kH61EHQdEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kH61EnQdEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kH61E3QdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kH61FHQdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kH61FXQdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kH61F3QdEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kH61FnQdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_mD_gMHQdEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_mD_gMXQdEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_mD-5KHQdEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_mD_gMnQdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_3Gq-EHQdEe2zsYbGoXS0Sg" name="préparation du PLF de la Phase d’élaboration et d’arbitrage" outgoing="_GZtDQHQeEe2zsYbGoXS0Sg" incoming="_162rMHQdEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_16rFAXQdEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_16rFAHQdEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_16rFAnQdEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_16rFA3QdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_16rFBHQdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_16rFBXQdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_16rFB3QdEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_16rFBnQdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_3GrlKXQdEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_3GrlKnQdEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_3GrlKHQdEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_3GrlK3QdEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="__m22cHQdEe2zsYbGoXS0Sg" name="conseil des Ministres&#xA;" actor="_kCx5kHQhEe2zsYbGoXS0Sg">
        <elements xmi:type="process:Task" xmi:id="_HmN5sHQeEe2zsYbGoXS0Sg" name="délibération des orientations générales du PLF" outgoing="_SR3kEHQeEe2zsYbGoXS0Sg" incoming="_GZtDQHQeEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GZkgYXQeEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GZkgYHQeEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GZkgYnQeEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GZkgY3QeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GZkgZHQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GZkgZXQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GZkgZ3QeEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GZkgZnQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_HmPH2HQeEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_HmPH2XQeEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_HmPH13QeEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_HmPH2nQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_OCdkYHQeEe2zsYbGoXS0Sg" name="Conseil du Gouvernement" actor="_mXZAgHQhEe2zsYbGoXS0Sg">
        <elements xmi:type="process:Task" xmi:id="_TQNboHQeEe2zsYbGoXS0Sg" name=" adoption le PLF " outgoing="_UrV84HQeEe2zsYbGoXS0Sg" incoming="_SR3kEHQeEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SRsk8XQeEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SRsk8HQeEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SRsk8nQeEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SRsk83QeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SRsk9HQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SRsk9XQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SRsk93QeEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SRsk9nQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_TQOCuXQeEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_TQOCunQeEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_TQOCuHQeEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_TQOCu3QeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_eJ4ecHQfEe2zsYbGoXS0Sg" name=" dépôt le PLF au bureau de la Chambre des Représentants" outgoing="_kVJjUHQeEe2zsYbGoXS0Sg _t7_sUHQfEe2zsYbGoXS0Sg" incoming="_UrV84HQeEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UrML4nQeEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UrML4XQeEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UrML43QeEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_UrML5HQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_UrML5XQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UrML5nQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_UrML6HQeEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_UrML53QeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_eJ5sk3QfEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_eJ5slHQfEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_eJ5sknQfEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_eJ5slXQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_hUWr0HQeEe2zsYbGoXS0Sg" name="chambre des représentants" actor="_ABUBAHQiEe2zsYbGoXS0Sg">
        <elements xmi:type="process:Task" xmi:id="_dnNPMHQfEe2zsYbGoXS0Sg" name="examen du PLF 1" outgoing="_idlvUHQfEe2zsYbGoXS0Sg" incoming="_kVJjUHQeEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kVBAcXQeEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kVBAcHQeEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kVBAcnQeEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kVBAc3QeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kVBAdHQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kVBAdXQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kVBAd3QeEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kVBAdnQeEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_dnPEZXQfEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_dnPEZnQfEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_dnPEZHQfEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_dnPEZ3QfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_wW958HQfEe2zsYbGoXS0Sg" name="vote sur le PLF 1" incoming="_idlvUHQfEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iddMcXQfEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iddMcHQfEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iddMcnQfEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_iddMc3QfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_iddMdHQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_iddMdXQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_iddMd3QfEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_iddMdnQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_wW_IGHQfEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_wW_IGXQfEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_wW_IF3QfEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_wW_IGnQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_9v3NsHQfEe2zsYbGoXS0Sg" name="adopter définitive le PLF" outgoing="_F3I20HQgEe2zsYbGoXS0Sg" incoming="_2z9LgHQfEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2z0ooXQfEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2z0ooHQfEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2z0oonQfEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2z0oo3QfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2z0opHQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2z0opXQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2z0op3QfEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2z0opnQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_9v4b2HQfEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_9v4b2XQfEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_9v4b13QfEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_9v4b2nQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_mvtEwHQfEe2zsYbGoXS0Sg" name="chambre des conseillers" actor="_Bk4FgHQiEe2zsYbGoXS0Sg">
        <elements xmi:type="process:Task" xmi:id="_vyjlUHQfEe2zsYbGoXS0Sg" name="examen du PLF 2" outgoing="_xEThEHQfEe2zsYbGoXS0Sg" incoming="_t7_sUHQfEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_t70tMXQfEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_t70tMHQfEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_t70tMnQfEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_t70tM3QfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_t70tNHQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_t70tNXQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_t70tN3QfEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_t70tNnQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_vykMaXQfEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_vykManQfEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_vykMaHQfEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_vykMa3QfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_yT12UHQfEe2zsYbGoXS0Sg" name="vote sur le PLF 2" outgoing="_2z9LgHQfEe2zsYbGoXS0Sg" incoming="_xEThEHQfEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xEMMUXQfEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xEMMUHQfEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xEMMUnQfEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xEMMU3QfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xEMMVHQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xEMMVXQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xEMMV3QfEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xEMMVnQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_yT3Ec3QfEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_yT3EdHQfEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_yT3EcnQfEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_yT3EdXQfEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_BkJXoHQgEe2zsYbGoXS0Sg" name="Etat" actor="_CyAnAHQiEe2zsYbGoXS0Sg">
        <elements xmi:type="process:Task" xmi:id="_Gm0AQHQgEe2zsYbGoXS0Sg" name="adoption finale du Projet de loi de Finance " outgoing="_JlU_0HQgEe2zsYbGoXS0Sg" incoming="_F3I20HQgEe2zsYbGoXS0Sg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F2_s4XQgEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F2_s4HQgEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F2_s4nQgEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_F2_s43QgEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_F2_s5HQgEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_F2_s5XQgEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_F2_s53QgEe2zsYbGoXS0Sg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_F2_s5nQgEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Gm0nWXQgEe2zsYbGoXS0Sg">
            <targetForm xmi:type="expression:Expression" xmi:id="_Gm0nWnQgEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Gm0nWHQgEe2zsYbGoXS0Sg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Gm1OYHQgEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_JlILgHQgEe2zsYbGoXS0Sg" name="End1" incoming="_JlU_0HQgEe2zsYbGoXS0Sg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JlJZoXQgEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JlJZoHQgEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JlJZonQgEe2zsYbGoXS0Sg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_ae_e9HQQEe2zsYbGoXS0Sg">
        <targetForm xmi:type="expression:Expression" xmi:id="_ae_e9XQQEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ae_e9nQQEe2zsYbGoXS0Sg">
        <targetForm xmi:type="expression:Expression" xmi:id="_ae_e93QQEe2zsYbGoXS0Sg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ae_e-HQQEe2zsYbGoXS0Sg" target="__8CIIHQQEe2zsYbGoXS0Sg" source="_ae_e43QQEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ae_e-XQQEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_ae_e-nQQEe2zsYbGoXS0Sg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_66YhQHQSEe2zsYbGoXS0Sg" target="_7-wIUHQSEe2zsYbGoXS0Sg" source="__8CIIHQQEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_66ZvYHQSEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_66ZvYXQSEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PEHPoHQTEe2zsYbGoXS0Sg" target="_Q4QGwHQTEe2zsYbGoXS0Sg" source="_7-wIUHQSEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PEH2sHQTEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_PEH2sXQTEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MsQK8HQUEe2zsYbGoXS0Sg" target="_NoqI0HQUEe2zsYbGoXS0Sg" source="_Q4QGwHQTEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MsQK8XQUEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_MsQK8nQUEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mdfe8HQVEe2zsYbGoXS0Sg" target="_6viJ4HQXEe2zsYbGoXS0Sg" source="_NoqI0HQUEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mdfe8XQVEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_mdfe8nQVEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_t2qaAHQXEe2zsYbGoXS0Sg" target="_5zeKQHQXEe2zsYbGoXS0Sg" source="_6viJ4HQXEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_t2qaAXQXEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_t2qaAnQXEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3NPu4HQXEe2zsYbGoXS0Sg" target="_5IO04HQXEe2zsYbGoXS0Sg" source="_5zeKQHQXEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3NPu4XQXEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_3NQV8HQXEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-sg80HQXEe2zsYbGoXS0Sg" target="_AQQAcHQYEe2zsYbGoXS0Sg" source="_5IO04HQXEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-shj4HQXEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_-shj4XQXEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HVO0MHQaEe2zsYbGoXS0Sg" target="_IkVEkHQaEe2zsYbGoXS0Sg" source="_AQQAcHQYEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HVO0MXQaEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_HVO0MnQaEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_J_FLUHQaEe2zsYbGoXS0Sg" target="_KnP-kHQaEe2zsYbGoXS0Sg" source="_IkVEkHQaEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_J_FLUXQaEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_J_FLUnQaEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WUawUHQaEe2zsYbGoXS0Sg" target="_dV0WgHQaEe2zsYbGoXS0Sg" source="_KnP-kHQaEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WUawUXQaEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_WUawUnQaEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_quKQoHQaEe2zsYbGoXS0Sg" target="_tYlPgHQaEe2zsYbGoXS0Sg" source="_dV0WgHQaEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_quKQoXQaEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_quKQonQaEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_88LOUHQcEe2zsYbGoXS0Sg" target="_9yoVMHQcEe2zsYbGoXS0Sg" source="_tYlPgHQaEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_88LOUXQcEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_88LOUnQcEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KFcKoHQdEe2zsYbGoXS0Sg" target="_L2R2IHQdEe2zsYbGoXS0Sg" source="_tYlPgHQaEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KFcKoXQdEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_KFcKonQdEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kIHCUHQdEe2zsYbGoXS0Sg" target="_mD-SEHQdEe2zsYbGoXS0Sg" source="_L2R2IHQdEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kIHCUXQdEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_kIHCUnQdEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_162rMHQdEe2zsYbGoXS0Sg" target="_3Gq-EHQdEe2zsYbGoXS0Sg" source="_mD-SEHQdEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_162rMXQdEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_162rMnQdEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GZtDQHQeEe2zsYbGoXS0Sg" target="_HmN5sHQeEe2zsYbGoXS0Sg" source="_3Gq-EHQdEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GZtqUHQeEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_GZtqUXQeEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SR3kEHQeEe2zsYbGoXS0Sg" target="_TQNboHQeEe2zsYbGoXS0Sg" source="_HmN5sHQeEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SR4LIHQeEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_SR4LIXQeEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UrV84HQeEe2zsYbGoXS0Sg" target="_eJ4ecHQfEe2zsYbGoXS0Sg" source="_TQNboHQeEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UrWj8HQeEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_UrWj8XQeEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kVJjUHQeEe2zsYbGoXS0Sg" target="_dnNPMHQfEe2zsYbGoXS0Sg" source="_eJ4ecHQfEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kVJjUXQeEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_kVJjUnQeEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_idlvUHQfEe2zsYbGoXS0Sg" target="_wW958HQfEe2zsYbGoXS0Sg" source="_dnNPMHQfEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_idlvUXQfEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_idlvUnQfEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_t7_sUHQfEe2zsYbGoXS0Sg" target="_vyjlUHQfEe2zsYbGoXS0Sg" source="_eJ4ecHQfEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_t7_sUXQfEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_t7_sUnQfEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xEThEHQfEe2zsYbGoXS0Sg" target="_yT12UHQfEe2zsYbGoXS0Sg" source="_vyjlUHQfEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xEThEXQfEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_xEUIIHQfEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2z9LgHQfEe2zsYbGoXS0Sg" target="_9v3NsHQfEe2zsYbGoXS0Sg" source="_yT12UHQfEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2z9ykHQfEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_2z9ykXQfEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_F3I20HQgEe2zsYbGoXS0Sg" target="_Gm0AQHQgEe2zsYbGoXS0Sg" source="_9v3NsHQfEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_F3I20XQgEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_F3I20nQgEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JlU_0HQgEe2zsYbGoXS0Sg" target="_JlILgHQgEe2zsYbGoXS0Sg" source="_Gm0AQHQgEe2zsYbGoXS0Sg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JlVm4HQgEe2zsYbGoXS0Sg"/>
        <condition xmi:type="expression:Expression" xmi:id="_JlVm4XQgEe2zsYbGoXS0Sg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_o4gu4HQgEe2zsYbGoXS0Sg" name="Ordonnateurs" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_yY0ngHQgEe2zsYbGoXS0Sg" name="commissions de programmation et de performance"/>
      <actors xmi:type="process:Actor" xmi:id="_3ZkkkHQgEe2zsYbGoXS0Sg" name="Chef de Gouvernement"/>
      <actors xmi:type="process:Actor" xmi:id="_8N4oIHQgEe2zsYbGoXS0Sg" name="départements ministériels et institution"/>
      <actors xmi:type="process:Actor" xmi:id="_K5A_0HQhEe2zsYbGoXS0Sg" name="ministre chargé des finances"/>
      <actors xmi:type="process:Actor" xmi:id="_Po4BMHQhEe2zsYbGoXS0Sg" name="commissions des finances du Parlement"/>
      <actors xmi:type="process:Actor" xmi:id="_Uw2AkHQhEe2zsYbGoXS0Sg" name="Ministère de l’EcoFinances et autres Ministères"/>
      <actors xmi:type="process:Actor" xmi:id="_kCx5kHQhEe2zsYbGoXS0Sg" name="conseil des Ministres"/>
      <actors xmi:type="process:Actor" xmi:id="_mXZAgHQhEe2zsYbGoXS0Sg" name="Conseil du Gouvernement"/>
      <actors xmi:type="process:Actor" xmi:id="_ABUBAHQiEe2zsYbGoXS0Sg" name="chambre des Représentants"/>
      <actors xmi:type="process:Actor" xmi:id="_Bk4FgHQiEe2zsYbGoXS0Sg" name="chambre des Conseillers"/>
      <actors xmi:type="process:Actor" xmi:id="_CyAnAHQiEe2zsYbGoXS0Sg" name="Etat"/>
      <contract xmi:type="process:Contract" xmi:id="_ae_e_HQQEe2zsYbGoXS0Sg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ae_e_XQQEe2zsYbGoXS0Sg">
        <name xmi:type="expression:Expression" xmi:id="_ae_e_nQQEe2zsYbGoXS0Sg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ae_e_3QQEe2zsYbGoXS0Sg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ae_fAHQQEe2zsYbGoXS0Sg">
        <name xmi:type="expression:Expression" xmi:id="_ae_fAXQQEe2zsYbGoXS0Sg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ae_fAnQQEe2zsYbGoXS0Sg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ae_fA3QQEe2zsYbGoXS0Sg">
        <name xmi:type="expression:Expression" xmi:id="_ae_fBHQQEe2zsYbGoXS0Sg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ae_fBXQQEe2zsYbGoXS0Sg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ae_fBnQQEe2zsYbGoXS0Sg">
        <name xmi:type="expression:Expression" xmi:id="_ae_fB3QQEe2zsYbGoXS0Sg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ae_fCHQQEe2zsYbGoXS0Sg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ae_fCXQQEe2zsYbGoXS0Sg">
        <name xmi:type="expression:Expression" xmi:id="_ae_fCnQQEe2zsYbGoXS0Sg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ae_fC3QQEe2zsYbGoXS0Sg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_ae_fDHQQEe2zsYbGoXS0Sg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_ae_fDXQQEe2zsYbGoXS0Sg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_ae_fDnQQEe2zsYbGoXS0Sg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_ae_fD3QQEe2zsYbGoXS0Sg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_ae_fEHQQEe2zsYbGoXS0Sg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_ae_fEXQQEe2zsYbGoXS0Sg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_ae_fEnQQEe2zsYbGoXS0Sg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_ae_fE3QQEe2zsYbGoXS0Sg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_ae_fFHQQEe2zsYbGoXS0Sg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_afAF8HQQEe2zsYbGoXS0Sg" type="Process" element="_ae_e4HQQEe2zsYbGoXS0Sg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_afAF8XQQEe2zsYbGoXS0Sg" type="2007" element="_ae_e4XQQEe2zsYbGoXS0Sg">
      <children xmi:type="notation:DecorationNode" xmi:id="_afAF8nQQEe2zsYbGoXS0Sg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_afAF83QQEe2zsYbGoXS0Sg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_afAF9HQQEe2zsYbGoXS0Sg" type="3007" element="_ae_e4nQQEe2zsYbGoXS0Sg">
          <children xmi:type="notation:DecorationNode" xmi:id="_afAF9XQQEe2zsYbGoXS0Sg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_afAF9nQQEe2zsYbGoXS0Sg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_afAF-nQQEe2zsYbGoXS0Sg" type="3002" element="_ae_e43QQEe2zsYbGoXS0Sg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_afAF-3QQEe2zsYbGoXS0Sg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_afAF_HQQEe2zsYbGoXS0Sg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_afAF_XQQEe2zsYbGoXS0Sg" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__8EkYHQQEe2zsYbGoXS0Sg" type="3005" element="__8CIIHQQEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__8FygHQQEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__8EkYXQQEe2zsYbGoXS0Sg" x="160" y="60" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7-x9gHQSEe2zsYbGoXS0Sg" type="3005" element="_7-wIUHQSEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_7-ykkHQSEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7-x9gXQSEe2zsYbGoXS0Sg" x="422" y="58" width="168" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9ypjWXQcEe2zsYbGoXS0Sg" type="3005" element="_9yoVMHQcEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9yqKYHQcEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9ypjWnQcEe2zsYbGoXS0Sg" x="1141" y="58" width="232" height="116"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_afAF_nQQEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_afAF_3QQEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_afAGAHQQEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_afAGAXQQEe2zsYbGoXS0Sg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_afAGAnQQEe2zsYbGoXS0Sg" x="48" y="10" width="1297" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_I277sHQTEe2zsYbGoXS0Sg" type="3007" element="_I26GgHQTEe2zsYbGoXS0Sg">
          <children xmi:type="notation:DecorationNode" xmi:id="_I28iwHQTEe2zsYbGoXS0Sg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_I28iwXQTEe2zsYbGoXS0Sg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Q4RU4HQTEe2zsYbGoXS0Sg" type="3005" element="_Q4QGwHQTEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Q4R78HQTEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q4RU4XQTEe2zsYbGoXS0Sg" x="167" y="61" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tYmdoHQaEe2zsYbGoXS0Sg" type="3005" element="_tYlPgHQaEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tYmdonQaEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tYmdoXQaEe2zsYbGoXS0Sg" x="1154" y="60" width="232" height="116"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_I277sXQTEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_I277snQTEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_I277s3QTEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_I29J0HQTEe2zsYbGoXS0Sg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_I277tHQTEe2zsYbGoXS0Sg" x="48" y="250" width="1671" height="342"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_sis0kHQTEe2zsYbGoXS0Sg" type="3007" element="_siqYUHQTEe2zsYbGoXS0Sg">
          <children xmi:type="notation:DecorationNode" xmi:id="_sitboHQTEe2zsYbGoXS0Sg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_sitboXQTEe2zsYbGoXS0Sg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_NorW8HQUEe2zsYbGoXS0Sg" type="3005" element="_NoqI0HQUEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Nor-AHQUEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NorW8XQUEe2zsYbGoXS0Sg" x="201" y="21" width="180" height="89"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_L2TEQHQdEe2zsYbGoXS0Sg" type="3005" element="_L2R2IHQdEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_L2TEQnQdEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L2TEQXQdEe2zsYbGoXS0Sg" x="756" y="142" width="180" height="89"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_sis0kXQTEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_sis0knQTEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_sis0k3QTEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_sitbonQTEe2zsYbGoXS0Sg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sis0lHQTEe2zsYbGoXS0Sg" x="48" y="500" width="1671" height="334"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_egC8sHQUEe2zsYbGoXS0Sg" type="3007" element="_egAgcHQUEe2zsYbGoXS0Sg">
          <children xmi:type="notation:DecorationNode" xmi:id="_egDjwHQUEe2zsYbGoXS0Sg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_egDjwXQUEe2zsYbGoXS0Sg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_6vj_EHQXEe2zsYbGoXS0Sg" type="3005" element="_6viJ4HQXEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6vj_EnQXEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6vj_EXQXEe2zsYbGoXS0Sg" x="231" y="56" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_egC8sXQUEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_egC8snQUEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_egC8s3QUEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_egDjwnQUEe2zsYbGoXS0Sg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_egC8tHQUEe2zsYbGoXS0Sg" x="48" y="750" width="1447" height="300"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_Hsjr4HQWEe2zsYbGoXS0Sg" type="3007" element="_HsgokHQWEe2zsYbGoXS0Sg">
          <children xmi:type="notation:DecorationNode" xmi:id="_HskS8HQWEe2zsYbGoXS0Sg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_HskS8XQWEe2zsYbGoXS0Sg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_5IQDAHQXEe2zsYbGoXS0Sg" type="3005" element="_5IO04HQXEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5IQqEHQXEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5IQDAXQXEe2zsYbGoXS0Sg" x="351" y="51" width="232" height="116"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5zfYY3QXEe2zsYbGoXS0Sg" type="3005" element="_5zeKQHQXEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5zf_cHQXEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5zfYZHQXEe2zsYbGoXS0Sg" x="48" y="41" width="260" height="129"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_AQR1oHQYEe2zsYbGoXS0Sg" type="3005" element="_AQQAcHQYEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_AQScsHQYEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AQR1oXQYEe2zsYbGoXS0Sg" x="623" y="51" width="232" height="116"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dV2LsHQaEe2zsYbGoXS0Sg" type="3005" element="_dV0WgHQaEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dV2LsnQaEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dV2LsXQaEe2zsYbGoXS0Sg" x="1211" y="116" width="285" height="142"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Hsjr4XQWEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Hsjr4nQWEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Hsjr43QWEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_HskS8nQWEe2zsYbGoXS0Sg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Hsjr5HQWEe2zsYbGoXS0Sg" x="48" y="1050" width="1447" height="300"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_8f1X8HQZEe2zsYbGoXS0Sg" type="3007" element="_8fziwHQZEe2zsYbGoXS0Sg">
          <children xmi:type="notation:DecorationNode" xmi:id="_8f1_A3QZEe2zsYbGoXS0Sg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_8f1_BHQZEe2zsYbGoXS0Sg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_IkWSsHQaEe2zsYbGoXS0Sg" type="3005" element="_IkVEkHQaEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IkW5wHQaEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IkWSsXQaEe2zsYbGoXS0Sg" x="251" y="92" width="152" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KnRMsHQaEe2zsYbGoXS0Sg" type="3005" element="_KnP-kHQaEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KnRMsnQaEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KnRMsXQaEe2zsYbGoXS0Sg" x="1030" y="92" width="260" height="129"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_8f1X8XQZEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_8f1_AHQZEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_8f1_AXQZEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_8f1_BXQZEe2zsYbGoXS0Sg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8f1_AnQZEe2zsYbGoXS0Sg" x="48" y="1350" width="1447" height="300"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_b6A_gHQdEe2zsYbGoXS0Sg" type="3007" element="_b5_xYHQdEe2zsYbGoXS0Sg">
          <children xmi:type="notation:DecorationNode" xmi:id="_b6BmkHQdEe2zsYbGoXS0Sg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_b6BmkXQdEe2zsYbGoXS0Sg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_mD_gM3QdEe2zsYbGoXS0Sg" type="3005" element="_mD-SEHQdEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mEAHQHQdEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mD_gNHQdEe2zsYbGoXS0Sg" x="651" y="162" width="205" height="102"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3GsMMHQdEe2zsYbGoXS0Sg" type="3005" element="_3Gq-EHQdEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_3GszQHQdEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3GsMMXQdEe2zsYbGoXS0Sg" x="1249" y="176" width="152" height="76"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_b6A_gXQdEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_b6A_gnQdEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_b6A_g3QdEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_b6BmknQdEe2zsYbGoXS0Sg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_b6A_hHQdEe2zsYbGoXS0Sg" x="48" y="1826" width="1671" height="340"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="__m4EkHQdEe2zsYbGoXS0Sg" type="3007" element="__m22cHQdEe2zsYbGoXS0Sg">
          <children xmi:type="notation:DecorationNode" xmi:id="__m4roHQdEe2zsYbGoXS0Sg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="__m4roXQdEe2zsYbGoXS0Sg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_HmQV8HQeEe2zsYbGoXS0Sg" type="3005" element="_HmN5sHQeEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HmQ9AHQeEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HmQV8XQeEe2zsYbGoXS0Sg" x="754" y="96" width="152" height="76"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="__m4EkXQdEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="__m4EknQdEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="__m4Ek3QdEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="__m4ronQdEe2zsYbGoXS0Sg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="__m4ElHQdEe2zsYbGoXS0Sg" x="48" y="2166" width="1671" height="300"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_OCeygHQeEe2zsYbGoXS0Sg" type="3007" element="_OCdkYHQeEe2zsYbGoXS0Sg">
          <children xmi:type="notation:DecorationNode" xmi:id="_OCeyhXQeEe2zsYbGoXS0Sg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_OCeyhnQeEe2zsYbGoXS0Sg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_TQOpwHQeEe2zsYbGoXS0Sg" type="3005" element="_TQNboHQeEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TQPQ0HQeEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TQOpwXQeEe2zsYbGoXS0Sg" x="497" y="64" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eJ5slnQfEe2zsYbGoXS0Sg" type="3005" element="_eJ4ecHQfEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eJ6ToHQfEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eJ5sl3QfEe2zsYbGoXS0Sg" x="749" y="60" width="152" height="76"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_OCeygXQeEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_OCeygnQeEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_OCeyg3QeEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_OCeyh3QeEe2zsYbGoXS0Sg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OCeyhHQeEe2zsYbGoXS0Sg" x="48" y="2466" width="1671" height="300"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_hUX58HQeEe2zsYbGoXS0Sg" type="3007" element="_hUWr0HQeEe2zsYbGoXS0Sg">
          <children xmi:type="notation:DecorationNode" xmi:id="_hUX59XQeEe2zsYbGoXS0Sg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_hUYhAHQeEe2zsYbGoXS0Sg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_dnPrcHQfEe2zsYbGoXS0Sg" type="3005" element="_dnNPMHQfEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dnQSgXQfEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dnQSgHQfEe2zsYbGoXS0Sg" x="418" y="92" width="137" height="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wW_IG3QfEe2zsYbGoXS0Sg" type="3005" element="_wW958HQfEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wW_vIHQfEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wW_IHHQfEe2zsYbGoXS0Sg" x="769" y="81" width="125" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9v5C4HQfEe2zsYbGoXS0Sg" type="3005" element="_9v3NsHQfEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9v5C4nQfEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9v5C4XQfEe2zsYbGoXS0Sg" x="1114" y="144" width="125" height="62"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_hUX58XQeEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_hUX58nQeEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_hUX583QeEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_hUYhAXQeEe2zsYbGoXS0Sg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hUX59HQeEe2zsYbGoXS0Sg" x="48" y="2766" width="1671" height="300"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_mvuS4HQfEe2zsYbGoXS0Sg" type="3007" element="_mvtEwHQfEe2zsYbGoXS0Sg">
          <children xmi:type="notation:DecorationNode" xmi:id="_mvu58HQfEe2zsYbGoXS0Sg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_mvu58XQfEe2zsYbGoXS0Sg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_vykzcHQfEe2zsYbGoXS0Sg" type="3005" element="_vyjlUHQfEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vylagHQfEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vykzcXQfEe2zsYbGoXS0Sg" x="274" y="48" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yT3rgHQfEe2zsYbGoXS0Sg" type="3005" element="_yT12UHQfEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_yT3rgnQfEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yT3rgXQfEe2zsYbGoXS0Sg" x="658" y="44" width="100" height="49"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_mvuS4XQfEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_mvuS4nQfEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_mvuS43QfEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_mvu58nQfEe2zsYbGoXS0Sg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mvuS5HQfEe2zsYbGoXS0Sg" x="48" y="3066" width="1671" height="300"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_BkKlwHQgEe2zsYbGoXS0Sg" type="3007" element="_BkJXoHQgEe2zsYbGoXS0Sg">
          <children xmi:type="notation:DecorationNode" xmi:id="_BkLM1HQgEe2zsYbGoXS0Sg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_BkLM1XQgEe2zsYbGoXS0Sg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Gm1OYXQgEe2zsYbGoXS0Sg" type="3005" element="_Gm0AQHQgEe2zsYbGoXS0Sg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Gm11cHQgEe2zsYbGoXS0Sg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Gm1OYnQgEe2zsYbGoXS0Sg" x="561" y="80" width="152" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JlLO0HQgEe2zsYbGoXS0Sg" type="3003" element="_JlILgHQgEe2zsYbGoXS0Sg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_JlL14HQgEe2zsYbGoXS0Sg" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_JlL14XQgEe2zsYbGoXS0Sg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JlLO0XQgEe2zsYbGoXS0Sg" x="935" y="89"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_BkLM0HQgEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_BkLM0XQgEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_BkLM0nQgEe2zsYbGoXS0Sg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_BkLM1nQgEe2zsYbGoXS0Sg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BkLM03QgEe2zsYbGoXS0Sg" x="48" y="3366" width="1671" height="300"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_afAGA3QQEe2zsYbGoXS0Sg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_afAGBHQQEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_afAGBXQQEe2zsYbGoXS0Sg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_afAGBnQQEe2zsYbGoXS0Sg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_afAGB3QQEe2zsYbGoXS0Sg" width="1694" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_afAGCHQQEe2zsYbGoXS0Sg"/>
    <edges xmi:type="notation:Connector" xmi:id="_afAGCXQQEe2zsYbGoXS0Sg" type="4001" element="_ae_e-HQQEe2zsYbGoXS0Sg" source="_afAF-nQQEe2zsYbGoXS0Sg" target="__8EkYHQQEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_afAGCnQQEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_afAGC3QQEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_afAGDHQQEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_afAGDXQQEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_66bkkHQSEe2zsYbGoXS0Sg" type="4001" element="_66YhQHQSEe2zsYbGoXS0Sg" source="__8EkYHQQEe2zsYbGoXS0Sg" target="_7-x9gHQSEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_66cysHQSEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_66cysXQSEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_66bkkXQSEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_66bkknQSEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PEJE0HQTEe2zsYbGoXS0Sg" type="4001" element="_PEHPoHQTEe2zsYbGoXS0Sg" source="_7-x9gHQSEe2zsYbGoXS0Sg" target="_Q4RU4HQTEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PEJr4HQTEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PEJr4XQTEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PEJE0XQTEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PEJE0nQTEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MsRZEHQUEe2zsYbGoXS0Sg" type="4001" element="_MsQK8HQUEe2zsYbGoXS0Sg" source="_Q4RU4HQTEe2zsYbGoXS0Sg" target="_NorW8HQUEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MsSAIHQUEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MsSAIXQUEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MsRZEXQUEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MsRZEnQUEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mdgtEHQVEe2zsYbGoXS0Sg" type="4001" element="_mdfe8HQVEe2zsYbGoXS0Sg" source="_NorW8HQUEe2zsYbGoXS0Sg" target="_6vj_EHQXEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mdhUIHQVEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mdhUIXQVEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mdgtEXQVEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mdgtEnQVEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_t2roIHQXEe2zsYbGoXS0Sg" type="4001" element="_t2qaAHQXEe2zsYbGoXS0Sg" source="_6vj_EHQXEe2zsYbGoXS0Sg" target="_5zfYY3QXEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_t2sPMHQXEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_t2sPMXQXEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_t2roIXQXEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_t2roInQXEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3NQ9AHQXEe2zsYbGoXS0Sg" type="4001" element="_3NPu4HQXEe2zsYbGoXS0Sg" source="_5zfYY3QXEe2zsYbGoXS0Sg" target="_5IQDAHQXEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3NRkEHQXEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3NRkEXQXEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3NQ9AXQXEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3NQ9AnQXEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-siyAHQXEe2zsYbGoXS0Sg" type="4001" element="_-sg80HQXEe2zsYbGoXS0Sg" source="_5IQDAHQXEe2zsYbGoXS0Sg" target="_AQR1oHQYEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-sjZEHQXEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-sjZEXQXEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-siyAXQXEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-siyAnQXEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HVQCUHQaEe2zsYbGoXS0Sg" type="4001" element="_HVO0MHQaEe2zsYbGoXS0Sg" source="_AQR1oHQYEe2zsYbGoXS0Sg" target="_IkWSsHQaEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HVQCU3QaEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HVQCVHQaEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HVQCUXQaEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HVQCUnQaEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_J_FyYHQaEe2zsYbGoXS0Sg" type="4001" element="_J_FLUHQaEe2zsYbGoXS0Sg" source="_IkWSsHQaEe2zsYbGoXS0Sg" target="_KnRMsHQaEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_J_GZcHQaEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_J_GZcXQaEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_J_FyYXQaEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_J_FyYnQaEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WUb-cHQaEe2zsYbGoXS0Sg" type="4001" element="_WUawUHQaEe2zsYbGoXS0Sg" source="_KnRMsHQaEe2zsYbGoXS0Sg" target="_dV2LsHQaEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WUclgHQaEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WUclgXQaEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WUb-cXQaEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WUb-cnQaEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_quK3sHQaEe2zsYbGoXS0Sg" type="4001" element="_quKQoHQaEe2zsYbGoXS0Sg" source="_dV2LsHQaEe2zsYbGoXS0Sg" target="_tYmdoHQaEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_quLewnQaEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_quLew3QaEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_quLewHQaEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_quLewXQaEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_88MccHQcEe2zsYbGoXS0Sg" type="4001" element="_88LOUHQcEe2zsYbGoXS0Sg" source="_tYmdoHQaEe2zsYbGoXS0Sg" target="_9ypjWXQcEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_88Mcc3QcEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_88McdHQcEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_88MccXQcEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_88MccnQcEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KFcxsHQdEe2zsYbGoXS0Sg" type="4001" element="_KFcKoHQdEe2zsYbGoXS0Sg" source="_tYmdoHQaEe2zsYbGoXS0Sg" target="_L2TEQHQdEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KFdYwnQdEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KFdYw3QdEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KFdYwHQdEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KFdYwXQdEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kIHpYHQdEe2zsYbGoXS0Sg" type="4001" element="_kIHCUHQdEe2zsYbGoXS0Sg" source="_L2TEQHQdEe2zsYbGoXS0Sg" target="_mD_gM3QdEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kIIQcHQdEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kIIQcXQdEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kIHpYXQdEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kIHpYnQdEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_163SQHQdEe2zsYbGoXS0Sg" type="4001" element="_162rMHQdEe2zsYbGoXS0Sg" source="_mD_gM3QdEe2zsYbGoXS0Sg" target="_3GsMMHQdEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1635UHQdEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1635UXQdEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_163SQXQdEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_163SQnQdEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GZuRYHQeEe2zsYbGoXS0Sg" type="4001" element="_GZtDQHQeEe2zsYbGoXS0Sg" source="_3GsMMHQdEe2zsYbGoXS0Sg" target="_HmQV8HQeEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GZuRY3QeEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GZu4cHQeEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GZuRYXQeEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GZuRYnQeEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SR4yMHQeEe2zsYbGoXS0Sg" type="4001" element="_SR3kEHQeEe2zsYbGoXS0Sg" source="_HmQV8HQeEe2zsYbGoXS0Sg" target="_TQOpwHQeEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SR4yM3QeEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SR4yNHQeEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SR4yMXQeEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SR4yMnQeEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UrXLAHQeEe2zsYbGoXS0Sg" type="4001" element="_UrV84HQeEe2zsYbGoXS0Sg" source="_TQOpwHQeEe2zsYbGoXS0Sg" target="_eJ5slnQfEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UrXyEHQeEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UrXyEXQeEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UrXLAXQeEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UrXLAnQeEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kVKKYHQeEe2zsYbGoXS0Sg" type="4001" element="_kVJjUHQeEe2zsYbGoXS0Sg" source="_eJ5slnQfEe2zsYbGoXS0Sg" target="_dnPrcHQfEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kVKxcHQeEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kVKxcXQeEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kVKKYXQeEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kVKKYnQeEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_idmWYHQfEe2zsYbGoXS0Sg" type="4001" element="_idlvUHQfEe2zsYbGoXS0Sg" source="_dnPrcHQfEe2zsYbGoXS0Sg" target="_wW_IG3QfEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_idm9cHQfEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_idm9cXQfEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_idmWYXQfEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_idmWYnQfEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_t8ATYHQfEe2zsYbGoXS0Sg" type="4001" element="_t7_sUHQfEe2zsYbGoXS0Sg" source="_eJ5slnQfEe2zsYbGoXS0Sg" target="_vykzcHQfEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_t8A6cHQfEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_t8A6cXQfEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_t8ATYXQfEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_t8ATYnQfEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xEUvMHQfEe2zsYbGoXS0Sg" type="4001" element="_xEThEHQfEe2zsYbGoXS0Sg" source="_vykzcHQfEe2zsYbGoXS0Sg" target="_yT3rgHQfEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xEUvM3QfEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xEVWQHQfEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xEUvMXQfEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xEUvMnQfEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2z-ZoHQfEe2zsYbGoXS0Sg" type="4001" element="_2z9LgHQfEe2zsYbGoXS0Sg" source="_yT3rgHQfEe2zsYbGoXS0Sg" target="_9v5C4HQfEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2z-Zo3QfEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2z-ZpHQfEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2z-ZoXQfEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2z-ZonQfEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_F3KE8HQgEe2zsYbGoXS0Sg" type="4001" element="_F3I20HQgEe2zsYbGoXS0Sg" source="_9v5C4HQfEe2zsYbGoXS0Sg" target="_Gm1OYXQgEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_F3KE83QgEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_F3KE9HQgEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_F3KE8XQgEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_F3KE8nQgEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JlWN8HQgEe2zsYbGoXS0Sg" type="4001" element="_JlU_0HQgEe2zsYbGoXS0Sg" source="_Gm1OYXQgEe2zsYbGoXS0Sg" target="_JlLO0HQgEe2zsYbGoXS0Sg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JlW1AHQgEe2zsYbGoXS0Sg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JlW1AXQgEe2zsYbGoXS0Sg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JlWN8XQgEe2zsYbGoXS0Sg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JlWN8nQgEe2zsYbGoXS0Sg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
